version: '3.1'

services:
  bmsisp:
    image: andrewjsc/bmsisp:0.1.4
    restart: always
    ports:
      - 5000:5000
    volumes:
      - bmsisp-volume:/app/found
      - /home/andrewjsc/dev/biometric-system-management/encodings:/app/encodings

volumes:
  bmsisp-volume:
