version: '3.1'

services:
  bmsisp:
    image: achuang/bmsisp:0.1.4
    restart: always
    ports:
      - 5000:5000
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - bmsisp-volume:/app/found
      - /home/andrewjsc/dev/biometric-system-management/encodings:/app/encodings
      - /home/andrewjsc/dev/biometric-system-management/templates:/app/templates
      - /home/andrewjsc/dev/biometric-system-management/server.py:/app/server.py

volumes:
  bmsisp-volume:
