version: '3.1'

services:
  bmsisp:
    image: achuang/bmsisp:0.1.3
    restart: always
    environment:
      FLASK_APP: server.py
    ports:
      - 5000:5000
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - bmsisp-volume:/app/found

volumes:
  bmsisp-volume:
