version: '3.2'

services:
  bmsisp:
    image: andrewjsc/bmsisp:mongo
    restart: always
    ports:
      - 5000:5000
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - bmsisp-volume:/app/found
      # - ./encodings:/app/encodings

  mongodb:
    image: mongo:4.0
    restart: always
    volumes:
      - mongo-volume

  mongo-setup:
    image: mongo:4.0
    volumes:
      - type: bind
        source: ./mongodb/dump.bak
        target: /dump.bak
      - ./mongodb/encodings_dump:/dump
    entrypoint: bash -c "mongodump --host mongodb -d bmsisp -o dump.bak && mongorestore --host mongodb --drop /dump"

volumes:
  bmsisp-volume:
  mongo-volume:
